version: '3.8'

services:
  ollama-proxy:
    build: .
    container_name: ollama-proxy
    ports:
      - "5950:5950"
    environment:
      - OLLAMA_ENDPOINT=http://host.docker.internal:11434  # For Docker Desktop on macOS
      - OLLAMA_MODEL=gpt-oss:20b
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5950/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
