services:
  # Next.js Frontend
  frontend:
    image: portfolio-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    depends_on:
      - ollama-proxy
    networks:
      - portfolio-network
    # healthcheck:
    #   test: ["CMD", "sh", "-c", "curl -f http://localhost:3000 > /dev/null 2>&1 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # FastAPI Ollama Proxy
  ollama-proxy:
    image: portfolio-proxy:latest
    build:
      context: ./ollama-proxy
      dockerfile: Dockerfile
    container_name: portfolio-ollama-proxy
    ports:
      - "5950:5950"
    environment:
      # Use host.docker.internal for macOS Docker Desktop
      - OLLAMA_ENDPOINT=http://host.docker.internal:11434
      - OLLAMA_MODEL=gpt-oss:20b
    restart: unless-stopped
    networks:
      - portfolio-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Fix host.docker.internal resolution
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5950/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - frontend
      - ollama-proxy
    restart: unless-stopped
    networks:
      - portfolio-network
    profiles:
      - production  # Only start with --profile production

networks:
  portfolio-network:
    driver: bridge
    name: portfolio-network

volumes:
  nginx-cache:
    driver: local
